apiVersion: v1
baseDomain: lab
capabilities:
  baselineCapabilitySet: None
  additionalEnabledCapabilities:
  - openshift-samples
  - Console
compute:
- name: worker
  replicas: 0 
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 1 
fips: false
metadata:
  name: okd
networking: 
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 192.168.0.0/24
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: 
sshKey: 
imageContentSources:
- mirrors:
  - 192.168.0.200:5000/okd
  source: quay.io/openshift/okd
- mirrors:
  - 192.168.0.200:5000/okd
  source: quay.io/openshift/okd-content

