variant: fcos
version: 1.4.0
ignition:
  config:
    merge:
      - local: master.ign
storage:
  files:
    - path: /etc/zincati/config.d/90-disable-feature.toml
      mode: 0644
      contents:
        inline: |
          [updates]
          enabled = false
    - path: /etc/hostname
      mode: 0420
      overwrite: true
      contents:
        inline: |
          master.okd.lab